//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinnerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public System.Guid BookmarkID { get; set; }
        public string BookmarkDescription { get; set; }
        public Nullable<int> BookmarkIndex { get; set; }
        public Nullable<int> BookmarkStatus { get; set; }
        public Nullable<System.DateTime> BookmarkCreateDate { get; set; }
        public Nullable<System.DateTime> BookmarkLastUpdate { get; set; }
        public string BookmarkAddress { get; set; }
    }
}
