//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinnerDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiningDbContext : DbContext
    {
        public MiningDbContext()
            : base("name=MiningDataEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MiningServer> MiningServers { get; set; }
        public virtual DbSet<ServerRegion> ServerRegions { get; set; }
        public virtual DbSet<MinerType> MinerTypes { get; set; }
        public virtual DbSet<Bookmark> Bookmarks { get; set; }
    }
}
