//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinnerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiningServer
    {
        public System.Guid ServerID { get; set; }
        public Nullable<System.Guid> RegionID { get; set; }
        public Nullable<System.Guid> MinerID { get; set; }
        public string ServerName { get; set; }
        public string ServerDescription { get; set; }
        public Nullable<int> ServerPort { get; set; }
        public string ServerAddress { get; set; }
        public Nullable<int> ServerStatus { get; set; }
        public Nullable<System.DateTime> ServerCreateDate { get; set; }
        public Nullable<System.DateTime> ServerLastUpdate { get; set; }
    
        public virtual ServerRegion ServerRegion { get; set; }
        public virtual MinerType MinerType { get; set; }
    }
}
