//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinnerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerRegion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServerRegion()
        {
            this.MiningServers = new HashSet<MiningServer>();
        }
    
        public System.Guid RegionID { get; set; }
        public string RegionName { get; set; }
        public string RegionDescription { get; set; }
        public Nullable<int> RegionStatus { get; set; }
        public Nullable<System.DateTime> RegionCreateDate { get; set; }
        public Nullable<System.DateTime> RegionLastUpdate { get; set; }
        public Nullable<int> RegionTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiningServer> MiningServers { get; set; }
    }
}
